# Generated by Django 5.2.1 on 2025-06-01 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Videos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline", models.CharField(blank=True, max_length=50)),
                ("discretion", models.TextField(blank=True)),
                ("video", models.FileField(blank=True, upload_to="uploads/videos")),
                (
                    "genre",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("crime", "Crime"),
                            ("romance", "Romance"),
                            ("drama", "Drama"),
                            ("comedy", "Comedy"),
                            ("horror", "Horror"),
                            ("documentation", "Documentation"),
                            ("adventure", "Adventure"),
                        ],
                        default="customer",
                        max_length=25,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("thumbnail", models.FileField(upload_to="uploads/thumbnails")),
            ],
        ),
        migrations.CreateModel(
            name="Profiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abstract_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
        ),
    ]
