# Generated by Django 5.2.1 on 2025-06-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profiles",
            name="email_is_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
