# Generated by Django 5.2.1 on 2025-06-07 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_app", "0002_profiles_email_is_confirmed"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline", models.CharField(max_length=50)),
                ("discretion", models.TextField()),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("crime", "Crime"),
                            ("romance", "Romance"),
                            ("drama", "Drama"),
                            ("comedy", "Comedy"),
                            ("horror", "Horror"),
                            ("documentation", "Documentation"),
                            ("adventure", "Adventure"),
                        ],
                        default="customer",
                        max_length=25,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "thumbnail",
                    models.FileField(blank=True, upload_to="uploads/thumbnails"),
                ),
                (
                    "original_file",
                    models.FileField(upload_to="uploads/videos/originals"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VideoFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resolution", models.CharField(max_length=10)),
                ("file", models.FileField(upload_to="uploads/videos/converted")),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="service_app.video",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Videos",
        ),
    ]
