# Generated by Django 5.2.1 on 2025-06-08 05:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_app", "0003_video_videofile_delete_videos"),
    ]

    operations = [
        migrations.AddField(
            model_name="profiles",
            name="email_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
