# Generated by Django 5.2.1 on 2025-06-14 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service_app", "0004_profiles_email_token"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="discretion",
            new_name="description",
        ),
    ]
