# Generated by Django 5.2.1 on 2025-06-15 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service_app", "0005_rename_discretion_video_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="original_file",
            new_name="url",
        ),
    ]
