# Generated by Django 5.2.1 on 2025-06-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_app", "0006_rename_original_file_video_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="genre",
            field=models.CharField(default="customer", max_length=65),
        ),
        migrations.DeleteModel(
            name="VideoFile",
        ),
    ]
