# Generated by Django 5.2.1 on 2025-06-21 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_app", "0007_alter_video_genre_delete_videofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("current_time", models.FloatField()),
                ("is_finished", models.BooleanField(default=False)),
                (
                    "profiles",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_progress",
                        to="service_app.profiles",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="service_app.video",
                    ),
                ),
            ],
        ),
    ]
