# Generated by Django 5.2.1 on 2025-07-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_app", "0008_videoprogress"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="current_convert_state",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="video",
            name="isConverted",
            field=models.BooleanField(default=False),
        ),
    ]
