# Generated by Django 5.2.1 on 2025-07-01 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service_app", "0009_video_current_convert_state_video_isconverted"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="isConverted",
            new_name="is_converted",
        ),
    ]
