# Generated by Django 5.2.1 on 2025-07-12 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service_app", "0010_rename_isconverted_video_is_converted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="current_convert_state",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
