# Generated by Django 5.2.1 on 2025-07-12 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0011_alter_video_current_convert_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentVideoConvertProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sliderId', models.IntegerField(blank=True, null=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_convert_progress', to='service_app.video')),
            ],
        ),
    ]
