# Generated by Django 5.2.1 on 2025-07-12 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0012_currentvideoconvertprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentvideoconvertprogress',
            name='sliderId',
        ),
    ]
